// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Do_an_mon_hoc.Models;

public partial class WishlistDTO_Add
{

    public int? UserId { get; set; }

    public int? ProductId { get; set; }
}