// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Do_an_mon_hoc.Models;

public partial class Order
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public string Address { get; set; }

    public double? Total { get; set; }

    public override string ToString()
    {
        return Id.ToString();
    }

    public string Note { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? UserId { get; set; }

    [Display(AutoGenerateField = false)]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual User User { get; set; }
}