// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Do_an_mon_hoc.Models;

public partial class Product
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public string Thumbnail { get; set; }

    public string Name { get; set; }

    public double? RegPrice { get; set; }

    public int? DiscountPercent { get; set; }

    public double? DiscountPrice { get; set; }

    public string Unit { get; set; }

    public int? Quantity { get; set; }

    public string Canonical { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? DeletedAt { get; set; }

    public double? Rating { get; set; }

    public string Article { get; set; }

    public int? IsFeatured { get; set; }

    [Display(AutoGenerateField = false)]
    public int? CategoryId { get; set; }

    [Display(AutoGenerateField = false)]
    public int? BrandId { get; set; }

    public int? IsVisible { get; set; }

    [ForeignKey("BrandId")]
    public virtual Brand Brand { get; set; }

    [Display(AutoGenerateField = false)]
    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    [ForeignKey("CategoryId")]
    public virtual Category Category { get; set; }

    [Display(AutoGenerateField = false)]
    public virtual ICollection<Gallery> Galleries { get; set; } = new List<Gallery>();

    [Display(AutoGenerateField = false)]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [Display(AutoGenerateField = false)]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    [Display(AutoGenerateField = false)]
    public virtual ICollection<SaleItem> SaleItems { get; set; } = new List<SaleItem>();

    [Display(AutoGenerateField = false)]
    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();

    public override string ToString()
    {
        return Id + ": " + Name;
    }
}