// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Do_an_mon_hoc.Models;

public partial class Review
{
    public int Id { get; set; }

    public int? Rating { get; set; }

    public string Title { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? ProductId { get; set; }

    public int? UserId { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}