// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Do_an_mon_hoc.Models;

public partial class User
{

    public override string ToString()
    {
        return Id.ToString() + ": " + Fullname; 
    }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public string PhoneNumber { get; set; }

    public string PasswordHash { get; set; }

    public string Fullname { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? Deleted { get; set; }

    [Display(AutoGenerateField = false)]
    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    [Display(AutoGenerateField = false)]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [Display(AutoGenerateField = false)]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    [Display(AutoGenerateField = false)]
    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();
}
